name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ~/dist
      
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ZanyLeonic/poweredby.leonic.co.uk
          token: '${{ secrets.PAT }}'

      - name: Deploying to repository
        run: |
          git checkout --orphan deploy
          git rm -rf .

          date > generated.txt
          echo 'poweredby.leonic.co.uk' > CNAME
          
          cp -r ~/dist/* .

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add -A
          git commit -m "Automated CI deployment"
          git push -f --set-upstream origin deploy